name: Release
run-name: Release => ${{  github.event.head_commit.message }}

on:
  push:
    branches: [main]

jobs:
  release-docker:
    uses: infitx-org/actions/.github/workflows/release-docker.yaml@main
    secrets:
      token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
